# Generated by Django 6.0.1 on 2026-01-28 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={'ordering': ['-created_at'], 'verbose_name': 'Membre'},
        ),
        migrations.RemoveField(
            model_name='member',
            name='name',
        ),
        migrations.RemoveField(
            model_name='member',
            name='post_name',
        ),
        migrations.AddField(
            model_name='member',
            name='client_type',
            field=models.CharField(choices=[('PARTICULIER', 'Particulier'), ('ENTREPRISE', 'Entreprise/Organisation')], default='PARTICULIER', max_length=20),
        ),
        migrations.AddField(
            model_name='member',
            name='full_name',
            field=models.CharField(default='', max_length=255, verbose_name='Nom Complet / Raison Sociale'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='id_card_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name="N° Pièce d'Identité"),
        ),
        migrations.AddField(
            model_name='member',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='Adresse Physique'),
        ),
        migrations.AlterField(
            model_name='member',
            name='phone',
            field=models.CharField(max_length=20, unique=True, verbose_name='Téléphone (+243...)'),
        ),
    ]
