# Generated by Django 6.0.1 on 2026-02-04 09:51

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_equipment_ref_code_alter_equipment_name_and_more'),
        ('rentals', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rental',
            name='equipment',
        ),
        migrations.RemoveField(
            model_name='rental',
            name='total_amount_initial',
        ),
        migrations.AddField(
            model_name='rental',
            name='actual_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rental',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rental',
            name='daily_rate_at_time',
            field=models.DecimalField(decimal_places=2, default=1, help_text='Prix/jour au moment de la signature', max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rental',
            name='unit',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, related_name='rentals', to='inventory.equipmentunit'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rental',
            name='status',
            field=models.CharField(choices=[('PENDING', 'En attente'), ('ACTIVE', 'En cours'), ('FINISHED', 'Terminé'), ('EXTENDED', 'Prolongé'), ('CANCELLED', 'Annulé')], default='ACTIVE', max_length=10),
        ),
        migrations.CreateModel(
            name='RentalExtension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_end_date', models.DateField()),
                ('new_end_date', models.DateField()),
                ('extension_date', models.DateTimeField(auto_now_add=True)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('rental', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extensions', to='rentals.rental')),
            ],
        ),
    ]
