# Generated by Django 6.0.1 on 2026-01-26 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('SIMPLE', 'Outil Simple'), ('COMPOUND', 'Échafaudage/Kit')], default='SIMPLE', max_length=10)),
                ('daily_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_under_maintenance', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('total_quantity', models.PositiveIntegerField()),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='inventory.equipment')),
            ],
        ),
    ]
