# Generated by Django 6.0.1 on 2026-01-28 12:50

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='is_under_maintenance',
        ),
        migrations.AddField(
            model_name='component',
            name='min_threshold',
            field=models.PositiveIntegerField(default=1, verbose_name="Seuil d'alerte"),
        ),
        migrations.AddField(
            model_name='equipment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='equipment',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='equipment/'),
        ),
        migrations.AlterField(
            model_name='component',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nom de la pièce'),
        ),
        migrations.AlterField(
            model_name='component',
            name='total_quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='Quantité Totale en Stock'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='category',
            field=models.CharField(choices=[('SIMPLE', 'Outil Simple'), ('COMPOUND', 'Échafaudage / Kit')], default='SIMPLE', max_length=10),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='daily_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix journalier ($)'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='name',
            field=models.CharField(max_length=150, verbose_name="Nom de l'équipement"),
        ),
        migrations.CreateModel(
            name='EquipmentUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internal_code', models.CharField(max_length=50, unique=True, verbose_name='Code Interne (ex: BET-001)')),
                ('status', models.CharField(choices=[('AVAILABLE', 'Disponible'), ('RENTED', 'En Location'), ('MAINTENANCE', 'En Réparation'), ('LOST', 'Perdu/Hors service')], default='AVAILABLE', max_length=20)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='inventory.equipment')),
            ],
        ),
    ]
