# Generated by Django 6.0.1 on 2026-01-29 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_remove_equipment_is_under_maintenance_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='component',
            old_name='total_quantity',
            new_name='quantity_required',
        ),
    ]
