# Generated by Django 6.0.1 on 2026-02-03 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_rename_total_quantity_component_quantity_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='ref_code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Référence Modèle (ex: BET350)'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='name',
            field=models.CharField(max_length=150, unique=True, verbose_name="Nom de l'équipement"),
        ),
        migrations.AlterUniqueTogether(
            name='component',
            unique_together={('equipment', 'name')},
        ),
    ]
